#!/bin/bash
# AUXILIARY SCRIPT
# DATE WRITTEN: MAY 13, 2021
# DATE UPDATED: AGUSUT 30, 2021
# PURPOSE: outputs compiled energies of individual edr in OCT/TYR - MONOTERPENE - DABIOTECH PROJECT

echo " "
echo " | AUXILIARY SCRIPT | OUTPUTS COMPILED ENERGIES OF INDIVIDUAL EDR | "
echo " "

# ========================================================
# ------------------    REMINDERS    ---------------------
# ========================================================

# 1. only works for production files labelled as: step7_production_(ID)
#
# 2. declare important variables in section I, for:
#    a. total trajectory files
#
# 3. run file in csrc as ./mergeedr.sh
# 
# 4. the following files are generated by this script:
#    a. ${sysname}_SYSREPORT.edr   (gmx encov)
#    b. ${sysname}_ENERGY.xvg      (gmx energy)
#    c. ${sysname}_SYSREPORT.log   (gmx energy)

# ========================================================                                                                                            
# -------------------    SECTIONS    ---------------------
# ========================================================

# I.   DECLARE VARIABLES
#
# II.  DETERMINE SYSTEM
#
# III. REGISTER ENERGY FILENAMES
#
# IV.  TALLY ALL ENERGY FILES
#
# V.   CONCATENATE ALL EDR FILES
#
# VI. OUTPUT DESIRED ENERGY REPORTS

# <=======================================================
# <==== I. DECLARE VARIABLES 
# <=======================================================

totraj=20

# <=======================================================
# <==== II. DETERMINE SYSTEM
# <=======================================================

[[ ! -f "step7_production_1.part0001.edr" ]] &&           #correcting syntax. 
mv step7_production_1.edr step7_production_1.part0001.edr
getname=$(pwd)
sysname=$(echo $getname | rev | cut -d/ -f1 | rev)

# <=======================================================
# <==== III. REGISTER ENERGY FILENAMES
# <=======================================================

outraj=0
while [[ $outraj -ne $totraj ]]
do

outraj=$((outraj + 1 ))
prodnc="step7_production_$outraj"
checkc="000${outraj}"
alignc=$(echo $checkc | rev | cut -b 1-4 | rev) 
suffxc="${prodnc}.part${alignc}"

# <=======================================================
# <==== IV. TALLY ALL ENERGY FILES
# <=======================================================

if [[ outtraj == 1 ]]; then
comped="$suffxc.edr"
else
comped="$comped $suffxc.edr"
fi
done

# <=======================================================
# <==== V. CONCATENATE ALL EDR FILES
# <=======================================================

gmx eneconv -f ${comped} -o ${sysname}_SYSREPORT.edr              #command to combine edr files 

# <=======================================================
# <==== VI. OUTPUT DESIRED ENERGY REPORTS
# <=======================================================

gmx energy -f ${sysname}_SYSREPORT.edr -o ${sysname}_ENERGY.xvg << EOF >> ${sysname}_SYSREPORT.log
Pot
Kin
Tot
Tem
Den
EOF

echo "...FILE/S GENERATED" &&
echo " " &&
[[ -f "${sysname}_SYSREPORT.edr" ]] &&
 echo "   ${sysname}_SYSREPORT.edr" &&
[[ -f "${sysname}_SYSREPORT.xvg" ]] &&
 echo "   ${sysname}_SYSREPORT.xvg" &&
[[ -f "${sysname}_ENERGY.xvg" ]] &&
 echo "   ${sysname}_ENERGY.xvg" &&

# ========================================================
# ------------------      END      -----------------------
# ========================================================

echo " " 
echo "...DONE"
echo " "

duration=$SECONDS
echo " | TIME ELAPSED: $(($duration / 60)) MINUTE/S and $(($duration % 60)) SECOND/S |"
echo " "
