#!/bin/bash
# AUXILIARY SCRIPT
# DATE WRITTEN: MAY 31, 2021
# DATE UPDATED: AGUSUT 30, 2021
# PURPOSE: combine all log files in OCT/TYR - MONOTERPENE - DABIOTECH PROJECT 

echo " "
echo " | AUXILIARY SCRIPT | COMBINE LOG FILES | "
echo " "

# ========================================================
# ------------------    REMINDERS    ---------------------
# ========================================================

# 1. only works for production files labelled as: step7_production_(ID)
# 
# 2. run file in csrc as ./mergelog.sh
#
# 3. the following files are generated by this script:
#    a. ${sysname}_OUTPUT.log

# ========================================================
# -------------------    SECTIONS    ---------------------
# ========================================================

# I.   DETERMINE SYSTEM
#                                                                                                                                                                                     
# II.  REGISTER LOG FILENAMES
#
# III. TALLY ALL LOG FILES
#
# IV.  CONCATENATE ALL LOG FILES

# <=======================================================
# <==== I. DETERMINE SYSTEM
# <=======================================================

getname=$(pwd)
sysname=$(echo $getname | rev | cut -d/ -f1 | rev)

# <=======================================================
# <==== II. REGISTER LOG FILENAMES
# <=======================================================

ls step*.log | sort --version-sort -f > list1.txt

outraj=0
while read p ; do
outraj=$((outraj + 1))

# <=======================================================
# <==== III. TALLY ALL LOG FILES
# <=======================================================

if [[ $outraj == 1 ]]; then
comped="$p"
else
comped="$comped $p"
fi

done < list1.txt
rm list1.txt

# <=======================================================
# <==== IV. CONCATENATE ALL LOG FILES 
# <=======================================================

cat ${comped} > ${sysname}_OUTPUT.log &&

echo "...FILE/S GENERATED" &&
echo " " &&
[[ -f "${sysname}_OUTPUT.log" ]] &&
echo "   ${sysname}_OUTPUT.log" && 

# ========================================================
# ------------------      END      -----------------------
# ========================================================

echo " " 
echo "...DONE"
echo " "

duration=$SECONDS
echo " | TIME ELAPSED: $(($duration / 60)) MINUTE/S and $(($duration % 60)) SECOND/S |"
echo " "
